; Generated by lua2llvmir
; LLVM IR for Lua 5.4 program

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

; Lua value types
%LuaValue = type { i32, double }
%LuaState = type opaque
%LuaFunction = type opaque

; Runtime function declarations
declare void @lua_pushinteger(%LuaState*, i64)
declare void @lua_pushnumber(%LuaState*, double)
declare void @lua_pushstring(%LuaState*, i8*)
declare void @lua_pushboolean(%LuaState*, i32)
declare void @lua_pushnil(%LuaState*)
declare i64 @lua_tointeger(%LuaState*, i32)
declare double @lua_tonumber(%LuaState*, i32)
declare i8* @lua_tostring(%LuaState*, i32)
declare void @lua_call(%LuaState*, i32, i32)
declare void @lua_getglobal(%LuaState*, i8*)
declare void @lua_setglobal(%LuaState*, i8*)
declare i32 @printf(i8*, ...)

; Function 0 (12 instructions, 4 constants)
define void @lua_function_0() {
entry:
  %r0 = alloca %LuaValue  ; Register 0
  %r1 = alloca %LuaValue  ; Register 1
  %r2 = alloca %LuaValue  ; Register 2
  %r3 = alloca %LuaValue  ; Register 3
  %r4 = alloca %LuaValue  ; Register 4
  %r5 = alloca %LuaValue  ; Register 5
  %r6 = alloca %LuaValue  ; Register 6

  ; PC=1: VARARGPREP (adjust vararg parameters)
  ; Vararg preparation
  ; PC=2: LOADI ; TODO: Implement opcode LOADI

  ; PC=3: LOADK R[1] := K[0]  ; Float constant: 3.14
  %tmp2 = insertvalue %LuaValue undef, i32 19, 0  ; LUA_VNUMFLT
  %tmp2_1 = insertvalue %LuaValue %tmp2, double 3.14, 1
  store %LuaValue %tmp2_1, %LuaValue* %r1
  ; PC=4: LOADK R[2] := K[1]  ; String constant: "Hello, LLVM!"
  %str3 = alloca [13 x i8]
  %tmp3 = insertvalue %LuaValue undef, i32 4, 0  ; LUA_VSTRING
  %tmp3_1 = insertvalue %LuaValue %tmp3, double 0.0, 1
  store %LuaValue %tmp3_1, %LuaValue* %r2
  ; PC=5: ADDI ; TODO: Implement opcode ADDI

  ; PC=6: MMBINI ; TODO: Implement opcode MMBINI

  ; PC=7: GETTABUP R[4] := UpValue[0][K[2]] ; Get global 'print'
  ; TODO: Implement global variable access for 'print'
  ; PC=8: LOADK R[5] := K[3]  ; String constant: "Result:"
  %str7 = alloca [8 x i8]
  %tmp7 = insertvalue %LuaValue undef, i32 4, 0  ; LUA_VSTRING
  %tmp7_1 = insertvalue %LuaValue %tmp7, double 0.0, 1
  store %LuaValue %tmp7_1, %LuaValue* %r5
  ; PC=9: MOVE R[6] := R[3]
  %tmp8 = load %LuaValue, %LuaValue* %r3
  store %LuaValue %tmp8, %LuaValue* %r6
  ; PC=10: CALL R[4](R[4+1]...R[4+3-1]) -> R[4]...R[4+1-2]
  ; Function call: 2 args, 0 results
  ; TODO: Implement function call
  ; PC=11: RETURN return R[3]...R[3+2-2]
  ; Return from function
  ret void
  ; PC=12: RETURN return R[4]...R[4+1-2]
  ; Return from function
  ret void
  ret void
}

; Main entry point
define i32 @main() {
entry:
  call void @lua_function_0()
  ret i32 0
}
