/*
** lua2llvmir.c - Convert Lua source code to LLVM IR
** This tool compiles Lua 5.4 source code to bytecode and then generates LLVM IR
*/

#define LUA_CORE

#include "lprefix.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "lua.h"
#include "lauxlib.h"
#include "ldebug.h"
#include "lobject.h"
#include "lopcodes.h"
#include "lopnames.h"
#include "lstate.h"
#include "lundump.h"

#define PROGNAME "lua2llvmir"

static const char* progname = PROGNAME;
static const char* input_file = NULL;
static const char* output_file = NULL;
static int verbose = 0;

static void fatal(const char* message) {
    fprintf(stderr, "%s: %s\n", progname, message);
    exit(EXIT_FAILURE);
}

static void usage(const char* message) {
    if (message && *message) {
        fprintf(stderr, "%s: %s\n", progname, message);
    }
    fprintf(stderr,
        "usage: %s [options] input.lua\n"
        "Convert Lua 5.4 source code to LLVM IR\n"
        "Available options are:\n"
        "  -o name  output to file 'name' (default is input.ll)\n"
        "  -v       verbose output\n"
        "  -h       show this help\n"
        , progname);
    exit(EXIT_FAILURE);
}

static int doargs(int argc, char* argv[]) {
    int i;
    if (argv[0] != NULL && *argv[0] != 0) progname = argv[0];
    
    for (i = 1; i < argc; i++) {
        if (*argv[i] != '-') {
            // First non-option argument is input file
            if (input_file == NULL) {
                input_file = argv[i];
            } else {
                usage("multiple input files not supported");
            }
        }
        else if (strcmp(argv[i], "-o") == 0) {
            if (++i >= argc) usage("'-o' needs argument");
            output_file = argv[i];
        }
        else if (strcmp(argv[i], "-v") == 0) {
            verbose = 1;
        }
        else if (strcmp(argv[i], "-h") == 0) {
            usage("");
        }
        else {
            usage(argv[i]);
        }
    }
    
    if (input_file == NULL) {
        usage("no input file given");
    }
    
    return i;
}

// Get the Proto from the top of the Lua stack
static const Proto* get_main_proto(lua_State* L) {
    const TValue* obj = s2v(L->top.p - 1);
    if (ttisLclosure(obj)) {
        return clLvalue(obj)->p;
    }
    return NULL;
}

// Generate LLVM IR header
static void generate_llvm_header(FILE* out) {
    fprintf(out, "; Generated by %s\n", PROGNAME);
    fprintf(out, "; LLVM IR for Lua 5.4 program\n\n");
    
    // Target information
    fprintf(out, "target datalayout = \"e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128\"\n");
    fprintf(out, "target triple = \"x86_64-pc-linux-gnu\"\n\n");
    
    // Lua value type declarations
    fprintf(out, "; Lua value types\n");
    fprintf(out, "%%LuaValue = type { i32, double }\n");
    fprintf(out, "%%LuaState = type opaque\n");
    fprintf(out, "%%LuaFunction = type opaque\n\n");
    
    // Runtime function declarations
    fprintf(out, "; Runtime function declarations\n");
    fprintf(out, "declare void @lua_pushinteger(%%LuaState*, i64)\n");
    fprintf(out, "declare void @lua_pushnumber(%%LuaState*, double)\n");
    fprintf(out, "declare void @lua_pushstring(%%LuaState*, i8*)\n");
    fprintf(out, "declare void @lua_pushboolean(%%LuaState*, i32)\n");
    fprintf(out, "declare void @lua_pushnil(%%LuaState*)\n");
    fprintf(out, "declare i64 @lua_tointeger(%%LuaState*, i32)\n");
    fprintf(out, "declare double @lua_tonumber(%%LuaState*, i32)\n");
    fprintf(out, "declare i8* @lua_tostring(%%LuaState*, i32)\n");
    fprintf(out, "declare void @lua_call(%%LuaState*, i32, i32)\n");
    fprintf(out, "declare void @lua_getglobal(%%LuaState*, i8*)\n");
    fprintf(out, "declare void @lua_setglobal(%%LuaState*, i8*)\n");
    fprintf(out, "declare i32 @printf(i8*, ...)\n\n");
}

// Generate LLVM IR for a constant
static void generate_constant(FILE* out, const Proto* f, int k_idx) {
    const TValue* k = &f->k[k_idx];
    
    switch (ttypetag(k)) {
        case LUA_VNUMINT:
            fprintf(out, "  ; Integer constant: %lld\n", (long long)ivalue(k));
            break;
        case LUA_VNUMFLT:
            fprintf(out, "  ; Float constant: %g\n", fltvalue(k));
            break;
        case LUA_VSHRSTR:
        case LUA_VLNGSTR: {
            const char* str = getstr(tsvalue(k));
            fprintf(out, "  ; String constant: \"%s\"\n", str);
            break;
        }
        case LUA_VNIL:
            fprintf(out, "  ; Nil constant\n");
            break;
        case LUA_VFALSE:
            fprintf(out, "  ; Boolean constant: false\n");
            break;
        case LUA_VTRUE:
            fprintf(out, "  ; Boolean constant: true\n");
            break;
        default:
            fprintf(out, "  ; Unknown constant type: %d\n", ttypetag(k));
            break;
    }
}

// Generate LLVM IR for a single Lua instruction
static void generate_instruction(FILE* out, const Proto* f, int pc) {
    Instruction instr = f->code[pc];
    OpCode op = GET_OPCODE(instr);
    int a = GETARG_A(instr);
    int b = GETARG_B(instr);
    int c = GETARG_C(instr);
    int bx = GETARG_Bx(instr);
    int sbx = GETARG_sBx(instr);
    
    fprintf(out, "  ; PC=%d: %s", pc + 1, opnames[op]);
    
    switch (op) {
        case OP_LOADK:
            fprintf(out, " R[%d] := K[%d]", a, bx);
            generate_constant(out, f, bx);
            
            // Load the constant based on its type
            {
                const TValue* k = &f->k[bx];
                switch (ttypetag(k)) {
                    case LUA_VNUMINT:
                        fprintf(out, "  %%tmp%d = insertvalue %%LuaValue undef, i32 3, 0  ; LUA_VNUMINT\n", pc);
                        fprintf(out, "  %%tmp%d_1 = insertvalue %%LuaValue %%tmp%d, double %g, 1\n", 
                               pc, pc, (double)ivalue(k));
                        fprintf(out, "  store %%LuaValue %%tmp%d_1, %%LuaValue* %%r%d\n", pc, a);
                        break;
                    case LUA_VNUMFLT:
                        fprintf(out, "  %%tmp%d = insertvalue %%LuaValue undef, i32 19, 0  ; LUA_VNUMFLT\n", pc);
                        fprintf(out, "  %%tmp%d_1 = insertvalue %%LuaValue %%tmp%d, double %g, 1\n", 
                               pc, pc, fltvalue(k));
                        fprintf(out, "  store %%LuaValue %%tmp%d_1, %%LuaValue* %%r%d\n", pc, a);
                        break;
                    case LUA_VSHRSTR:
                    case LUA_VLNGSTR: {
                        const char* str = getstr(tsvalue(k));
                        // For strings, we'll need to create a global string constant
                        fprintf(out, "  %%str%d = alloca [%zu x i8]\n", pc, strlen(str) + 1);
                        fprintf(out, "  %%tmp%d = insertvalue %%LuaValue undef, i32 4, 0  ; LUA_VSTRING\n", pc);
                        fprintf(out, "  %%tmp%d_1 = insertvalue %%LuaValue %%tmp%d, double 0.0, 1\n", pc, pc);
                        fprintf(out, "  store %%LuaValue %%tmp%d_1, %%LuaValue* %%r%d\n", pc, a);
                        break;
                    }
                    default:
                        fprintf(out, "  ; TODO: Handle constant type %d\n", ttypetag(k));
                        break;
                }
            }
            break;
            
        case OP_GETTABUP:
            fprintf(out, " R[%d] := UpValue[%d][K[%d]]", a, b, c);
            if (b == 0 && f->sizeupvalues > 0) {  // Usually _ENV
                const TValue* k = &f->k[c];
                if (ttisstring(k)) {
                    const char* name = getstr(tsvalue(k));
                    fprintf(out, " ; Get global '%s'\n", name);
                    fprintf(out, "  ; TODO: Implement global variable access for '%s'\n", name);
                }
            }
            break;
            
        case OP_CALL:
            fprintf(out, " R[%d](R[%d+1]...R[%d+%d-1]) -> R[%d]...R[%d+%d-2]", a, a, a, b, a, a, c);
            fprintf(out, "\n  ; Function call: %d args, %d results\n", b - 1, c - 1);
            fprintf(out, "  ; TODO: Implement function call\n");
            break;
            
        case OP_RETURN:
            fprintf(out, " return R[%d]...R[%d+%d-2]", a, a, b);
            fprintf(out, "\n  ; Return from function\n");
            fprintf(out, "  ret void\n");
            break;
            
        case OP_VARARGPREP:
            fprintf(out, " (adjust vararg parameters)");
            fprintf(out, "\n  ; Vararg preparation\n");
            break;
            
        case OP_MOVE:
            fprintf(out, " R[%d] := R[%d]", a, b);
            fprintf(out, "\n  %%tmp%d = load %%LuaValue, %%LuaValue* %%r%d\n", pc, b);
            fprintf(out, "  store %%LuaValue %%tmp%d, %%LuaValue* %%r%d\n", pc, a);
            break;
            
        case OP_ADD:
            fprintf(out, " R[%d] := R[%d] + R[%d]", a, b, c);
            fprintf(out, "\n  ; TODO: Implement addition\n");
            break;
            
        default:
            fprintf(out, " ; TODO: Implement opcode %s\n", opnames[op]);
            break;
    }
    
    if (op != OP_RETURN && op != OP_VARARGPREP && op != OP_MOVE && op != OP_LOADK && 
        op != OP_GETTABUP && op != OP_CALL) {
        fprintf(out, "\n");
    }
}

// Generate LLVM IR for a Lua function (Proto)
static void generate_function(FILE* out, const Proto* f, int func_id) {
    fprintf(out, "; Function %d (%d instructions, %d constants)\n", 
            func_id, f->sizecode, f->sizek);
    fprintf(out, "define void @lua_function_%d() {\n", func_id);
    fprintf(out, "entry:\n");
    
    // Allocate registers
    for (int i = 0; i < f->maxstacksize; i++) {
        fprintf(out, "  %%r%d = alloca %%LuaValue  ; Register %d\n", i, i);
    }
    fprintf(out, "\n");
    
    // Generate code for each instruction
    for (int pc = 0; pc < f->sizecode; pc++) {
        generate_instruction(out, f, pc);
    }
    
    // Ensure the function ends with a return
    fprintf(out, "  ret void\n");
    fprintf(out, "}\n\n");
}

// Main LLVM generation function
static void generate_llvm_ir(const Proto* main_proto, FILE* out) {
    generate_llvm_header(out);
    
    // Generate the main function
    generate_function(out, main_proto, 0);
    
    // Generate nested functions
    for (int i = 0; i < main_proto->sizep; i++) {
        generate_function(out, main_proto->p[i], i + 1);
    }
    
    // Generate main entry point
    fprintf(out, "; Main entry point\n");
    fprintf(out, "define i32 @main() {\n");
    fprintf(out, "entry:\n");
    fprintf(out, "  call void @lua_function_0()\n");
    fprintf(out, "  ret i32 0\n");
    fprintf(out, "}\n");
}

static int compile_lua_to_bytecode(lua_State* L, const char* filename) {
    int result = luaL_loadfile(L, filename);
    if (result != LUA_OK) {
        fprintf(stderr, "Error loading file '%s': %s\n", filename, lua_tostring(L, -1));
        return 0;
    }
    return 1;
}

int main(int argc, char* argv[]) {
    lua_State* L;
    const Proto* main_proto;
    FILE* out;
    
    // Parse command line arguments
    doargs(argc, argv);
    
    // Set default output file if not specified
    if (output_file == NULL) {
        size_t len = strlen(input_file);
        char* default_output = malloc(len + 4);
        strcpy(default_output, input_file);
        // Replace .lua extension with .ll
        char* dot = strrchr(default_output, '.');
        if (dot && strcmp(dot, ".lua") == 0) {
            strcpy(dot, ".ll");
        } else {
            strcat(default_output, ".ll");
        }
        output_file = default_output;
    }
    
    if (verbose) {
        printf("Input file: %s\n", input_file);
        printf("Output file: %s\n", output_file);
    }
    
    // Initialize Lua state
    L = luaL_newstate();
    if (L == NULL) {
        fatal("cannot create Lua state: not enough memory");
    }
    
    // Compile Lua source to bytecode
    if (!compile_lua_to_bytecode(L, input_file)) {
        lua_close(L);
        exit(EXIT_FAILURE);
    }
    
    // Get the main function's Proto
    main_proto = get_main_proto(L);
    if (main_proto == NULL) {
        fatal("failed to get main function prototype");
    }
    
    if (verbose) {
        printf("Main function: %d instructions, %d constants, %d nested functions\n",
               main_proto->sizecode, main_proto->sizek, main_proto->sizep);
    }
    
    // Open output file
    out = fopen(output_file, "w");
    if (out == NULL) {
        fprintf(stderr, "Cannot open output file '%s'\n", output_file);
        lua_close(L);
        exit(EXIT_FAILURE);
    }
    
    // Generate LLVM IR
    generate_llvm_ir(main_proto, out);
    
    // Clean up
    fclose(out);
    lua_close(L);
    
    if (verbose) {
        printf("LLVM IR generated successfully: %s\n", output_file);
    }
    
    return 0;
}