; Generated by lua2llvmir
; LLVM IR for Lua 5.4 program

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

; Lua value types
%LuaValue = type { i32, double }
%LuaState = type opaque
%LuaFunction = type opaque

; Runtime function declarations
declare void @lua_pushinteger(%LuaState*, i64)
declare void @lua_pushnumber(%LuaState*, double)
declare void @lua_pushstring(%LuaState*, i8*)
declare void @lua_pushboolean(%LuaState*, i32)
declare void @lua_pushnil(%LuaState*)
declare i64 @lua_tointeger(%LuaState*, i32)
declare double @lua_tonumber(%LuaState*, i32)
declare i8* @lua_tostring(%LuaState*, i32)
declare void @lua_call(%LuaState*, i32, i32)
declare void @lua_getglobal(%LuaState*, i8*)
declare void @lua_setglobal(%LuaState*, i8*)
declare i32 @printf(i8*, ...)

; Function 0 (5 instructions, 2 constants)
define void @lua_function_0() {
entry:
  %r0 = alloca %LuaValue  ; Register 0
  %r1 = alloca %LuaValue  ; Register 1

  ; PC=1: VARARGPREP (adjust vararg parameters)
  ; Vararg preparation
  ; PC=2: GETTABUP R[0] := UpValue[0][K[0]] ; Get global 'print'
  ; TODO: Implement global variable access for 'print'
  ; PC=3: LOADK R[1] := K[1]  ; String constant: "Hello from luac!"
  %str2 = alloca [17 x i8]
  %tmp2 = insertvalue %LuaValue undef, i32 4, 0  ; LUA_VSTRING
  %tmp2_1 = insertvalue %LuaValue %tmp2, double 0.0, 1
  store %LuaValue %tmp2_1, %LuaValue* %r1
  ; PC=4: CALL R[0](R[0+1]...R[0+2-1]) -> R[0]...R[0+1-2]
  ; Function call: 1 args, 0 results
  ; TODO: Implement function call
  ; PC=5: RETURN return R[0]...R[0+1-2]
  ; Return from function
  ret void
  ret void
}

; Main entry point
define i32 @main() {
entry:
  call void @lua_function_0()
  ret i32 0
}
